In [2]:
from sklearn.linear_model import LogisticRegression
import numpy as np

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
import pickle


In [3]:
new_x_train = np.load("hehe/new_x_train_v2.npy")
y_train = np.load("hehe/y_train.npy")
new_x_test = np.load("hehe/new_x_test_v2.npy")
y_test = np.load("hehe/y_test.npy")

In [4]:
model = LogisticRegression()
model.fit(new_x_train, y_train)

y_pred = model.predict_proba(new_x_train)[:, 1]
performance = roc_auc_score(y_train, y_pred)
print performance

y_pred = model.predict_proba(new_x_test)[:, 1]
performance = roc_auc_score(y_test, y_pred)
print performance

print model.coef_

0.9987758277009018
0.74177194826034
[[ 33.76768064  -8.5699916  -14.03948383]]


In [78]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=10, random_state=0, verbose=False)
model.fit(new_x_train, y_train)
y_pred = model.predict_proba(new_x_train)[:, 1]
performance = roc_auc_score(y_train, y_pred)
print performance

y_pred = model.predict_proba(new_x_test)[:, 1]
performance = roc_auc_score(y_test, y_pred)
print performance

0.9882494855427814
0.7960648632304121


In [137]:
new_x_test.shape

(12934, 3)

In [259]:
new_predictions = np.add(0.3*new_x_test[:, 0], 0.3333333*new_x_test[:, 1], 0.3333*new_x_test[:, 2])

In [260]:
new_predictions

array([0.40519908, 0.08843412, 0.4525867 , ..., 0.02705977, 0.14576112,
       0.15932251])

In [261]:
roc_auc_score(y_test, new_predictions)

0.8010749830321018

In [185]:
new_predictions

array([0.70983554, 0.14725949, 0.79581425, ..., 0.04746725, 0.24816099,
       0.27411317])

In [117]:
def ensemble(predictions_1, predictions_2):
    # should be same size
    new_predictions = []
    for i, _ in enumerate(predictions_1):
        pred1 = predictions_1[i]
        pred2 = predictions_2[i]
        if pred1 < 0.5 and pred2 < 0.5:
            # THIS CASE HAPPENS THE MOT
            new_predictions.append(0.5*pred1 + 0.5*pred2)
        elif pred1 > 0.5 and pred2 > 0.5:
            new_predictions.append(0.5*pred1 + 0.5*pred2)
        else:
            new_predictions.append(0.5*pred1 + 0.5*pred2)
#         new_predictions.append(0.5*pred1 + 0.5*pred2)
    new_predictions = np.array(new_predictions)
    return new_predictions

test_predictions = ensemble(new_x_test[:, 0], new_x_test[:, 1])
roc_auc_score(y_test, test_predictions)

0.801069733053922