In [5]:
from sklearn.linear_model import LogisticRegression
import numpy as np

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import roc_auc_score
import pickle


/anaconda/lib/python2.7/site-packages/lightgbm/__init__.py:46: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you don't need to install the gcc compiler anymore.
Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", UserWarning)


In [44]:
new_x_train = np.load("hehe/new_x_train.npy")
y_train = np.load("hehe/y_train.npy")
new_x_test = np.load("hehe/new_x_test.npy")
y_test = np.load("hehe/y_test.npy")

In [45]:
model = LogisticRegression()
model.fit(new_x_train, y_train)

y_pred = model.predict_proba(new_x_train)[:, 1]
performance = roc_auc_score(y_train, y_pred)
print performance

y_pred = model.predict_proba(new_x_test)[:, 1]
performance = roc_auc_score(y_test, y_pred)
print performance

0.9982579022180602
0.7502748191702828


In [50]:
new_predictions = np.add(0.5*new_x_test[:, 0], 0.5*new_x_test[:, 1])

In [51]:
new_predictions

array([0.64181095, 0.13752063, 0.71785814, ..., 0.04288218, 0.22848146,
       0.25069358])

In [52]:
roc_auc_score(y_test, new_predictions)

0.801069733053922

array([1, 0, 1, ..., 0, 0, 0])

In [49]:
new_predictions

array([0.63412397, 0.14554702, 0.70551754, ..., 0.0422885 , 0.2348187 ,
       0.2539931 ])